import unittest
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
import time
from random import seed
from random import randint
from random_username.generate import generate_username

password = randint(888888888, 8888888888888)
username_list = generate_username(500)
name = ''
surname = ''
for i in username_list:
    if 4 <= len(i) <= 10:
        username = i
        surname = i
        name = i


class Acceptance(unittest.TestCase):
    def test_acceptance(self):
        driver = webdriver.Chrome(executable_path="chromedriver.exe")
        driver.get("http://127.0.0.1:5000/sign_up")
        driver.maximize_window()
        driver.find_element_by_xpath("/html/body/div[1]/div/div/form/div[2]/input").send_keys("a")
        driver.find_element_by_xpath("/html/body/div[1]/div/div/form/div[4]/input").send_keys("b")
        driver.find_element_by_xpath("/html/body/div[1]/div/div/form/div[8]/input").send_keys("ab")
        driver.find_element_by_xpath("/html/body/div[1]/div/div/form/div[10]/input").send_keys("112")
        driver.find_element_by_xpath("/html/body/div[1]/div/div/form/div[11]/button").click()
        time.sleep(1)
        driver.find_element_by_xpath("/html/body/div[1]/div/div/form/div[2]/input").clear()
        driver.find_element_by_xpath("/html/body/div[1]/div/div/form/div[2]/input").send_keys(username)
        driver.find_element_by_xpath("/html/body/div[1]/div/div/form/div[11]/button").click()
        time.sleep(1)
        driver.find_element_by_xpath("/html/body/div[1]/div/div/form/div[4]/input").clear()
        driver.find_element_by_xpath("/html/body/div[1]/div/div/form/div[4]/input").send_keys(surname)
        driver.find_element_by_xpath("/html/body/div[1]/div/div/form/div[11]/button").click()
        time.sleep(1)
        driver.find_element_by_xpath("/html/body/div[1]/div/div/form/div[8]/input").clear()
        driver.find_element_by_xpath("/html/body/div[1]/div/div/form/div[8]/input").send_keys("enes")
        driver.find_element_by_xpath("/html/body/div[1]/div/div/form/div[11]/button").click()
        time.sleep(1)
        driver.find_element_by_xpath("/html/body/div[1]/div/div/form/div[10]/input").clear()
        driver.find_element_by_xpath("/html/body/div[1]/div/div/form/div[10]/input").send_keys(password)
        driver.find_element_by_xpath("/html/body/div[1]/div/div/form/div[11]/button").click()
        time.sleep(1)
        driver.find_element_by_xpath("/html/body/div[1]/div/div/form/div[3]/input").send_keys(username)
        driver.find_element_by_xpath("/html/body/div[1]/div/div/form/div[5]/input").send_keys(surname)
        driver.find_element_by_xpath("/html/body/div[1]/div/div/form/div[9]/input").send_keys(username)
        driver.find_element_by_xpath("/html/body/div[1]/div/div/form/div[11]/input").send_keys(password)
        driver.find_element_by_xpath("/html/body/div[1]/div/div/form/div[12]/button").click()
        time.sleep(1)
        driver.find_element_by_xpath("/html/body/div[1]/div/div/form/div[3]/input").send_keys("enes")
        driver.find_element_by_xpath("/html/body/div[1]/div/div/form/div[5]/input").send_keys("11111saasd")
        driver.find_element_by_xpath("/html/body/div[1]/div/div/form/div[6]/button").click()
        time.sleep(1)
        driver.find_element_by_xpath("/html/body/div[1]/div/div/form/div[3]/input").send_keys(username)
        driver.find_element_by_xpath("/html/body/div[1]/div/div/form/div[5]/input").send_keys(password)
        driver.find_element_by_xpath("/html/body/div[1]/div/div/form/div[6]/button").click()
        driver.find_element_by_xpath("/html/body/div[3]/div[4]/ul/li[1]/a").click()
        driver.find_element_by_xpath("//*[@id='home']/form/div/div/button").click()
        driver.find_element_by_xpath("//*[@id='subject']").send_keys("Hi my name is ", name, ".",
                                                                     "Thank you checking my profile.")
        driver.find_element_by_xpath("//*[@id='city']").send_keys("Istanbul")
        email = username + "@mail.com"
        driver.find_element_by_xpath("//*[@id='email']").send_keys(email)
        driver.find_element_by_xpath("//*[@id='uni']").send_keys("Istanbul Technical University")
        driver.find_element_by_xpath("//*[@id='tel']").send_keys("+90 555 555 55 55")
        driver.find_element_by_xpath("//*[@id='home']/form/div/div/div/div[3]/div/button").click()
        driver.find_element_by_xpath("//*[@id='home']/form/div/div/button[1]").click()
        driver.find_element_by_xpath("//*[@id='subject']").clear()
        driver.find_element_by_xpath("//*[@id='subject']").send_keys("UPDATE UPDATE UPDATE UPDATE UPDATE UPDATE")
        driver.find_element_by_xpath("//*[@id='city']").clear()
        driver.find_element_by_xpath("//*[@id='city']").send_keys("Istanbul UPDATE")
        email = "UPDATE" + email
        driver.find_element_by_xpath("//*[@id='email']").clear()
        driver.find_element_by_xpath("//*[@id='email']").send_keys(email)
        driver.find_element_by_xpath("//*[@id='uni']").clear()
        driver.find_element_by_xpath("//*[@id='uni']").send_keys("UPDATE Technical University")
        driver.find_element_by_xpath("//*[@id='tel']").clear()
        driver.find_element_by_xpath("//*[@id='tel']").send_keys("+90 111 111 11 11")
        driver.find_element_by_xpath("//*[@id='home']/form/div/div/div[2]/div/button").click()
        driver.find_element_by_xpath("//*[@id='home']/form/div/div/button[2]").click()
        driver.get("http://127.0.0.1:5000/profile")
        driver.find_element_by_xpath("/html/body/div[3]/div[4]/ul/li[2]/a").click()
        driver.find_element_by_xpath("/html/body/div/div/div/div[16]/div/div[2]/form/button/strong").click()
        driver.find_element_by_xpath("/html/body/nav/div/div/div/span[2]/a").click()
        driver.find_element_by_xpath("/html/body/div[3]/div[4]/ul/li[3]/a").click()
        driver.find_element_by_xpath("/html/body/div[2]/div/div/div[1]/div/div[2]/form/button/strong").click()
        time.sleep(2)
        driver.get("http://127.0.0.1:5000/profile")
        driver.find_element_by_xpath("/html/body/div[3]/div[4]/ul/li[5]/a").click()
        driver.find_element_by_xpath("//*[@id='home']/form/div/div/button").click()
        driver.find_element_by_xpath("//*[@id='home']/form/div/div/div[1]/div[1]/input").send_keys(
            "https://www.researchgate.net/publication/326319011_Intellectual_capital_knowledge_management_and_social_capital_within_the_ICT_sector_in_Jordan")
        driver.find_element_by_xpath("//*[@id='home']/form/div/div/div[1]/div[2]/input").send_keys(
            "Intellectual capital, knowledge management and social capital within the ICT sector in Jordan")
        driver.find_element_by_xpath("//*[@id='home']/form/div/div/div[2]/div/button").click()
        driver.find_element_by_xpath("//*[@id='home']/form/div/div/table/tbody/tr[2]/td[4]/button/strong").click()
        driver.find_element_by_xpath("//*[@id='item2']").click()
        driver.find_element_by_xpath("//*[@id='iiitem2']/div/form/button[3]/strong").click()
        bookmark_address = "http://127.0.0.1:5000/profile/bookmarks/" + username
        driver.get(bookmark_address)
        driver.find_element_by_xpath("//*[@id='home']/form/div/div/table/tbody/tr[2]/td[4]/button/strong").click()
        driver.find_element_by_xpath("//*[@id='item2']").click()
        driver.find_element_by_xpath("//*[@id='iiitem2']/div/form/button[3]/strong").click()
        bookmark_address = "http://127.0.0.1:5000/profile/bookmarks/" + username
        driver.get(bookmark_address)
        driver.find_element_by_xpath("//*[@id='home']/form/div/div/table/tbody/tr[2]/td[1]/label/input").click()
        driver.find_element_by_xpath("//*[@id='home']/form/div/div/div/div/button").click()
        time.sleep(2)
        delete_account_page = "http://127.0.0.1:5000/profile/delete_account/" + username
        driver.get(delete_account_page)
        driver.find_element_by_xpath("//*[@id='home']/div[2]/div/div/div/form/div/input").send_keys("asdasdasd")
        driver.find_element_by_xpath("//*[@id='home']/div[2]/div/div/div/form/button").click()
        time.sleep(1)
        driver.get(delete_account_page)
        driver.find_element_by_xpath("//*[@id='home']/div[2]/div/div/div/form/div/input").send_keys(password)
        driver.find_element_by_xpath("//*[@id='home']/div[2]/div/div/div/form/button").click()
        driver.find_element_by_xpath("//*[@id='warningAuthors']/button").click()
        time.sleep(2)
        driver.find_element_by_xpath("//*[@id='Demo']/a[4]").click()
        driver.find_element_by_xpath("//*[@id='author']/div/form[1]/input").send_keys("Samer Eid Dahiyat")
        driver.find_element_by_xpath("//*[@id='author']/div/form[1]/div/button/strong").click()
        driver.find_element_by_xpath("//*[@id='home']/div[2]/div/div/div/table/tbody/tr[1]/td/button").click()
        driver.find_element_by_xpath("//*[@id='home']/div[2]/div/div/div/table/tbody/tr[1]/td/button").click()
        time.sleep(2)
        driver.get("http://127.0.0.1:5000/dashboard")
        driver.find_element_by_xpath("//*[@id='warningAuthors']/button").click()
        time.sleep(2)
        driver.find_element_by_xpath("//*[@id='Demo']/a[3]").click()
        driver.find_element_by_xpath("//*[@id='keyword']/div/form[1]/input").send_keys("ai")
        driver.find_element_by_xpath("//*[@id='keyword']/div/form[1]/div/button/strong").click()
        driver.find_element_by_xpath("//*[@id='home']/div[2]/div/div/div/table/tbody/tr[1]/td/button").click()
        time.sleep(2)
        driver.get("http://127.0.0.1:5000/dashboard")
        driver.find_element_by_xpath("//*[@id='url']/div/form[2]/button/strong").click()
        time.sleep(2)
        driver.get("http://127.0.0.1:5000/dashboard")
        driver.find_element_by_xpath("//*[@id='url']/div/form[1]/input").send_keys("https://www.resealedsfctual.com")
        driver.find_element_by_xpath("//*[@id='url']/div/form[1]/div/button/strong").click()
        time.sleep(2)
        driver.find_element_by_xpath("//*[@id='url']/div/form[1]/input").send_keys(
            "https://www.researchgate.net/publication/326319011_Intellectual_capital_knowledge_management_and_social_capital_within_the_ICT_sector_in_Jordan")
        driver.find_element_by_xpath("//*[@id='url']/div/form[1]/div/button/strong").click()
        driver.find_element_by_xpath("//*[@id='buttons']/a[2]").click()
        driver.find_element_by_xpath("//*[@id='savebutton']").click()
        driver.find_element_by_xpath("//*[@id='jsonCitations']").click()
        driver.find_element_by_xpath("//*[@id='csvCitations']").click()
        driver.find_element_by_xpath("//*[@id='jsonReferences']").click()
        driver.find_element_by_xpath("//*[@id='csvReferences']").click()
        driver.find_element_by_xpath("//*[@id='jsonPaper']").click()
        driver.find_element_by_xpath("//*[@id='csvPaper']").click()
        driver.find_element_by_xpath("//*[@id='buttons']/a[2]").click()
        driver.find_element_by_xpath("//*[@id='howtowork']").click()
        time.sleep(1)
        driver.find_element_by_xpath("//*[@id='howtowork1']/div/span").click()
        driver.find_element_by_xpath("//*[@id='item2']").click()
        driver.find_element_by_xpath("//*[@id='iiitem2']/div/form/button[1]/strong").click()
        time.sleep(2)
        driver.find_element_by_xpath("//*[@id='item2']").click()
        driver.find_element_by_xpath("//*[@id='iiitem2']/div/form/button[1]/strong").click()
        print("Acceptance Test is successful")
        time.sleep(2)
        driver.quit()
